// ignore_for_file: use_build_context_synchronously
import 'package:flutter/foundation.dart'; // For web check
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'moderator_nav.dart'; // Assuming this file contains navigateModeratorIndex

// Category colors and icons mapping
const Map<String, Map<String, dynamic>> categoryConfig = {
  'Health & Welfare': {'color': Color(0xFF4CAF50), 'icon': Icons.favorite},
  'Brgy Clearance/Permit Process': {
    'color': Color(0xFFFFA726),
    'icon': Icons.assignment,
  },
  'Brgy Hall Schedule': {'color': Color(0xFF29B6F6), 'icon': Icons.schedule},
  'Emergency Services': {'color': Color(0xFFEF5350), 'icon': Icons.emergency},
  'Events & Announcements': {'color': Color(0xFF7E57C2), 'icon': Icons.event},
  'Community Programs': {'color': Color(0xFF26A69A), 'icon': Icons.groups},
  'Other': {'color': Color(0xFF9E9E9E), 'icon': Icons.info},
};

class ModeratorHomePage extends StatefulWidget {
  const ModeratorHomePage({super.key});

  @override
  State<ModeratorHomePage> createState() => _ModeratorHomePageState();
}

class _ModeratorHomePageState extends State<ModeratorHomePage> {
  final FirebaseFirestore _db = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  int _selectedIndex = 0;

  // Search State
  final TextEditingController _searchController = TextEditingController();
  String _searchQuery = '';

  // Track expanded state for service cards using Document IDs
  final Map<String, bool> _expandedStates = {};

  // Global Key for ScaffoldMessenger to constrain SnackBars inside PhoneFrame (for web)
  final GlobalKey<ScaffoldMessengerState> _scaffoldMessengerKey =
      GlobalKey<ScaffoldMessengerState>();

  // Stream for Barangay Services
  final Stream<QuerySnapshot> _servicesStream = FirebaseFirestore.instance
      .collection('barangay_services')
      .orderBy('createdAt', descending: true)
      .snapshots();

  Future<void> _ensureSignedIn() async {
    try {
      if (_auth.currentUser == null) {
        await _auth.signInAnonymously();
      }
    } catch (_) {
      // ignore auth errors
    }
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  void _onItemTapped(int index) {
    navigateModeratorIndex(
      context,
      index,
      currentIndex: _selectedIndex,
      onSamePage: (i) => setState(() => _selectedIndex = i),
    );
  }

  void _updateSearch(String query) {
    setState(() {
      _searchQuery = query.toLowerCase();
    });
  }

  // --- SAFE UI Helpers (For web containment) ---

  // Helper to show dialogs constrained within the PhoneFrame
  void _safeShowDialog({required Widget Function(BuildContext) builder}) {
    // In web mode, we want the dialog to be constrained inside the PhoneFrame.
    if (kIsWeb && mounted) {
      final scaffoldContext = _scaffoldMessengerKey.currentContext;
      if (scaffoldContext != null) {
        // We use the scaffoldContext to ensure the dialog appears relative to the phone frame.
        showDialog(
          context: scaffoldContext,
          barrierDismissible: true,
          builder: (BuildContext dialogContext) {
            // The AlertDialog wrapper ensures correct styling and positioning inside the frame.
            return AlertDialog(
              // **FIX: The AlertDialog itself must NOT be const if its children use .shadeXXX methods.**
              insetPadding: const EdgeInsets.symmetric(
                horizontal: 20,
                vertical: 24,
              ),
              scrollable: true,
              backgroundColor: Colors.white,
              surfaceTintColor: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
              titlePadding: const EdgeInsets.fromLTRB(24, 24, 24, 0),
              contentPadding: const EdgeInsets.fromLTRB(24, 20, 24, 24),
              actionsPadding: const EdgeInsets.fromLTRB(24, 0, 24, 24),
              // We return the content generated by the original dialog builder function
              content: builder(dialogContext),
            );
          },
        );
      }
    } else {
      // Default behavior for mobile
      showDialog(context: context, barrierDismissible: true, builder: builder);
    }
  }

  // Helper to show snackbars constrained within the PhoneFrame
  void _safeShowSnackbar(String message, [Color? color]) {
    final messenger =
        _scaffoldMessengerKey.currentState ?? ScaffoldMessenger.of(context);
    messenger.showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: color,
        duration: const Duration(milliseconds: 1500),
      ),
    );
  }

  // --- CRUD LOGIC ---

  Future<void> _addService(String title, String category, String steps) async {
    await _ensureSignedIn();
    await _db.collection('barangay_services').add({
      'title': title,
      'category': category,
      'steps': steps,
      'createdAt': FieldValue.serverTimestamp(),
    });
  }

  Future<void> _updateService(
    String docId,
    String title,
    String category,
    String steps,
  ) async {
    await _db.collection('barangay_services').doc(docId).update({
      'title': title,
      'category': category,
      'steps': steps,
      'updatedAt': FieldValue.serverTimestamp(),
    });
  }

  Future<void> _deleteService(String docId) async {
    await _db.collection('barangay_services').doc(docId).delete();
  }

  // --- DIALOGS ---

  // Enhanced Input Decoration
  InputDecoration _buildInputDecoration({
    required String label,
    required String hint,
    required IconData icon,
  }) {
    // NOTE: This uses Colors.blue.shade700 and Colors.grey.shadeXXX, so it must be NON-CONST.
    return InputDecoration(
      labelText: label,
      hintText: hint,
      filled: true,
      fillColor: Colors.grey.shade50,
      prefixIcon: Icon(icon, color: Colors.blue.shade700),
      labelStyle: TextStyle(color: Colors.grey.shade700),
      hintStyle: TextStyle(color: Colors.grey.shade400),
      contentPadding: const EdgeInsets.symmetric(vertical: 16, horizontal: 20),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(color: Colors.grey.shade300),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(color: Colors.grey.shade200),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(color: Colors.blue.shade700, width: 2),
      ),
    );
  }

  void _showAddServiceDialog() {
    final titleCtrl = TextEditingController();
    final stepsCtrl = TextEditingController();
    String selectedCategory = categoryConfig.keys.first;

    _safeShowDialog(
      builder: (ctx) {
        // For web, _safeShowDialog returns an AlertDialog, so we only return the content.
        if (kIsWeb) {
          return _buildAddDialogContent(
            ctx,
            titleCtrl,
            stepsCtrl,
            selectedCategory,
            (v) => selectedCategory = v, // update local variable
          );
        }

        // For mobile, we return the full AlertDialog as before.
        return AlertDialog(
          scrollable: true,
          backgroundColor: Colors.white,
          surfaceTintColor: Colors.white,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20),
          ),
          titlePadding: const EdgeInsets.fromLTRB(24, 24, 24, 0),
          contentPadding: const EdgeInsets.fromLTRB(24, 20, 24, 24),
          actionsPadding: const EdgeInsets.fromLTRB(24, 0, 24, 24),
          insetPadding: const EdgeInsets.symmetric(
            horizontal: 20,
            vertical: 24,
          ),
          title: _buildDialogTitle(
            Icons.post_add_rounded,
            'Add Service',
            Colors.blue,
          ),
          content: _buildAddEditContent(
            titleCtrl,
            stepsCtrl,
            selectedCategory,
            (v) => selectedCategory = v!,
          ),
          actions: _buildAddActions(
            ctx,
            titleCtrl,
            stepsCtrl,
            () => selectedCategory,
          ),
        );
      },
    );
  }

  // Extracted Dialog Content for re-use and web compatibility
  Widget _buildAddDialogContent(
    BuildContext ctx,
    TextEditingController titleCtrl,
    TextEditingController stepsCtrl,
    String selectedCategory,
    void Function(String) onCategoryChanged,
  ) {
    // **FIX: This entire Column cannot be const if its children use .shadeXXX**
    return Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        _buildDialogTitle(Icons.post_add_rounded, 'Add Service', Colors.blue),
        const SizedBox(height: 20),
        _buildAddEditContent(
          titleCtrl,
          stepsCtrl,
          selectedCategory,
          onCategoryChanged,
        ),
        const SizedBox(height: 20),
        Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: _buildAddActions(
            ctx,
            titleCtrl,
            stepsCtrl,
            () => selectedCategory,
          ),
        ),
      ],
    );
  }

  List<Widget> _buildAddActions(
    BuildContext ctx,
    TextEditingController titleCtrl,
    TextEditingController stepsCtrl,
    String Function() getCategory,
  ) {
    return [
      TextButton(
        onPressed: () => Navigator.of(ctx).pop(),
        style: TextButton.styleFrom(foregroundColor: Colors.grey.shade700),
        child: const Text(
          'Cancel',
          style: TextStyle(fontWeight: FontWeight.w600),
        ),
      ),
      ElevatedButton.icon(
        onPressed: () async {
          final title = titleCtrl.text.trim();
          final steps = stepsCtrl.text.trim();
          final selectedCategory = getCategory();
          if (title.isEmpty || steps.isEmpty) {
            _safeShowSnackbar('Please fill all fields');
            return;
          }

          try {
            await _addService(title, selectedCategory, steps);
            Navigator.of(ctx).pop();
            _safeShowSnackbar('Service added successfully', Colors.green);
          } catch (e) {
            _safeShowSnackbar('Error adding service: $e', Colors.red);
          }
        },
        // NOTE: Uses Colors.blue.shade700, so it must be non-const.
        style: ElevatedButton.styleFrom(
          backgroundColor: Colors.blue.shade700,
          foregroundColor: Colors.white,
          elevation: 2,
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
          shape: const StadiumBorder(),
        ),
        icon: const Icon(Icons.check_rounded, size: 20),
        label: const Text('Add', style: TextStyle(fontWeight: FontWeight.bold)),
      ),
    ];
  }

  void _showEditServiceDialog(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    final titleCtrl = TextEditingController(text: data['title']);
    final stepsCtrl = TextEditingController(text: data['steps']);
    String selectedCategory = data['category'] ?? categoryConfig.keys.first;

    if (!categoryConfig.containsKey(selectedCategory)) {
      selectedCategory = categoryConfig.keys.first;
    }

    _safeShowDialog(
      builder: (ctx) {
        if (kIsWeb) {
          return _buildEditDialogContent(
            ctx,
            doc,
            titleCtrl,
            stepsCtrl,
            selectedCategory,
            (v) => selectedCategory = v,
          );
        }

        return AlertDialog(
          scrollable: true,
          backgroundColor: Colors.white,
          surfaceTintColor: Colors.white,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20),
          ),
          titlePadding: const EdgeInsets.fromLTRB(24, 24, 24, 0),
          contentPadding: const EdgeInsets.fromLTRB(24, 20, 24, 24),
          actionsPadding: const EdgeInsets.fromLTRB(24, 0, 24, 24),
          insetPadding: const EdgeInsets.symmetric(
            horizontal: 20,
            vertical: 24,
          ),
          title: _buildDialogTitle(
            Icons.edit_rounded,
            'Edit Service',
            Colors.orange,
          ),
          content: _buildAddEditContent(
            titleCtrl,
            stepsCtrl,
            selectedCategory,
            (v) => selectedCategory = v!,
          ),
          actions: _buildEditActions(
            ctx,
            doc.id,
            titleCtrl,
            stepsCtrl,
            () => selectedCategory,
          ),
        );
      },
    );
  }

  // Extracted Dialog Content for re-use and web compatibility
  Widget _buildEditDialogContent(
    BuildContext ctx,
    DocumentSnapshot doc,
    TextEditingController titleCtrl,
    TextEditingController stepsCtrl,
    String selectedCategory,
    void Function(String) onCategoryChanged,
  ) {
    // **FIX: This entire Column cannot be const if its children use .shadeXXX**
    return Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        _buildDialogTitle(Icons.edit_rounded, 'Edit Service', Colors.orange),
        const SizedBox(height: 20),
        _buildAddEditContent(
          titleCtrl,
          stepsCtrl,
          selectedCategory,
          onCategoryChanged,
        ),
        const SizedBox(height: 20),
        Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: _buildEditActions(
            ctx,
            doc.id,
            titleCtrl,
            stepsCtrl,
            () => selectedCategory,
          ),
        ),
      ],
    );
  }

  List<Widget> _buildEditActions(
    BuildContext ctx,
    String docId,
    TextEditingController titleCtrl,
    TextEditingController stepsCtrl,
    String Function() getCategory,
  ) {
    return [
      TextButton(
        onPressed: () => Navigator.of(ctx).pop(),
        style: TextButton.styleFrom(foregroundColor: Colors.grey.shade700),
        child: const Text(
          'Cancel',
          style: TextStyle(fontWeight: FontWeight.w600),
        ),
      ),
      ElevatedButton.icon(
        onPressed: () {
          final title = titleCtrl.text.trim();
          final steps = stepsCtrl.text.trim();
          final selectedCategory = getCategory();
          if (title.isEmpty || steps.isEmpty) {
            _safeShowSnackbar('Please fill all fields');
            return;
          }
          _updateService(docId, title, selectedCategory, steps);
          Navigator.of(ctx).pop();
          _safeShowSnackbar('Service updated');
        },
        // NOTE: Uses Colors.orange.shade700, so it must be non-const.
        style: ElevatedButton.styleFrom(
          backgroundColor: Colors.orange.shade700,
          foregroundColor: Colors.white,
          elevation: 2,
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
          shape: const StadiumBorder(),
        ),
        icon: const Icon(Icons.check_rounded, size: 20),
        label: const Text(
          'Update',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
      ),
    ];
  }

  Widget _buildDialogTitle(IconData icon, String title, MaterialColor color) {
    // **FIX: This container uses color.shade50 and color.shade700, so it must NOT be const.**
    return Row(
      children: [
        Container(
          padding: const EdgeInsets.all(8),
          decoration: BoxDecoration(
            color: color.shade50, // Non-const call
            borderRadius: BorderRadius.circular(8),
          ),
          child: Icon(
            icon,
            color: color.shade700, // Non-const call
            size: 28,
          ),
        ),
        const SizedBox(width: 16),
        Expanded(
          child: Text(
            title,
            style: const TextStyle(
              color: Colors.black87,
              fontSize: 22,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildAddEditContent(
    TextEditingController titleCtrl,
    TextEditingController stepsCtrl,
    String selectedCategory,
    void Function(String) onCategoryChanged,
  ) {
    // NOTE: Uses _buildInputDecoration which is non-const.
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        TextField(
          controller: titleCtrl,
          style: const TextStyle(color: Colors.black87),
          decoration: _buildInputDecoration(
            label: 'Service Title',
            hint: 'e.g. Barangay Clearance',
            icon: Icons.title_rounded,
          ),
        ),
        const SizedBox(height: 16),
        DropdownButtonFormField<String>(
          value: selectedCategory,
          items: categoryConfig.keys.map((k) {
            return DropdownMenuItem(value: k, child: Text(k));
          }).toList(),
          onChanged: (v) => onCategoryChanged(v!),
          decoration: _buildInputDecoration(
            label: 'Category',
            hint: 'Select Category',
            icon: Icons.category_outlined,
          ),
          style: const TextStyle(color: Colors.black87, fontSize: 16),
          dropdownColor: Colors.white,
        ),
        const SizedBox(height: 16),
        TextField(
          controller: stepsCtrl,
          // FIX 2: Stable fixed height text box (min=max)
          minLines: 6,
          maxLines: 6,
          style: const TextStyle(color: Colors.black87),
          decoration: _buildInputDecoration(
            label: 'Steps / Requirements',
            hint: '1. Bring valid ID\n2. Fill out form...',
            icon: Icons.format_list_numbered_rounded,
          ),
        ),
      ],
    );
  }

  void _showDeleteConfirmDialog(String docId) {
    _safeShowDialog(
      builder: (ctx) => AlertDialog(
        // The AlertDialog itself is not const (whether via _safeShowDialog or directly)
        backgroundColor: Colors.white,
        surfaceTintColor: Colors.white,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: const Text(
          'Delete Service',
          style: TextStyle(fontWeight: FontWeight.bold, color: Colors.black87),
        ),
        // FIX 3: Visible text color
        content: const Text(
          'Are you sure you want to delete this service?',
          style: TextStyle(color: Colors.black87),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(),
            child: const Text('Cancel', style: TextStyle(color: Colors.grey)),
          ),
          // FIX 3: Visible Red Button
          ElevatedButton(
            onPressed: () {
              _deleteService(docId);
              Navigator.of(ctx).pop();
              _safeShowSnackbar('Service deleted');
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.red,
              foregroundColor: Colors.white,
              shape: const StadiumBorder(),
            ),
            child: const Text(
              'Delete',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }

  // --- WIDGET BUILDERS ---

  Widget _buildHeader() {
    // NOTE: This uses Colors.blue.shadeXXX, so it must be non-const.
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: const BorderRadius.only(
          bottomLeft: Radius.circular(24),
          bottomRight: Radius.circular(24),
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 20.0),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: Colors.blue.shade50, // Non-const call
              shape: BoxShape.circle,
            ),
            child: Icon(
              Icons.home_rounded,
              color: Colors.blue.shade700, // Non-const call
              size: 24,
            ),
          ),
          const SizedBox(width: 12),
          RichText(
            text: TextSpan(
              children: [
                const TextSpan(
                  text: 'iB',
                  style: TextStyle(
                    fontSize: 24,
                    fontWeight: FontWeight.w800,
                    color: Colors.blue,
                    letterSpacing: -0.5,
                  ),
                ),
                TextSpan(
                  text: 'rgy',
                  style: TextStyle(
                    fontSize: 24,
                    fontWeight: FontWeight.w800,
                    color: Colors.blue.shade900, // Non-const call
                    letterSpacing: -0.5,
                  ),
                ),
              ],
            ),
          ),
          const Spacer(),
        ],
      ),
    );
  }

  Widget _buildSearchBar() {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.03),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: TextField(
        controller: _searchController,
        onChanged: _updateSearch,
        // FIX: Black text
        style: const TextStyle(color: Colors.black),
        decoration: InputDecoration(
          hintText: "Search services, forms...",
          hintStyle: TextStyle(color: Colors.grey.shade400, fontSize: 14),
          prefixIcon: Icon(Icons.search, color: Colors.grey.shade400),
          border: InputBorder.none,
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 20,
            vertical: 14,
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title, VoidCallback onAdd) {
    return Row(
      children: [
        const Text(
          // Text is const
          "Barangay Services",
          style: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.bold,
            color: Colors.black87,
          ),
        ),
        const Spacer(),
        // FIX: Plain Plus Icon (No background)
        IconButton(
          onPressed: onAdd,
          icon: const Icon(Icons.add, color: Colors.blue, size: 28),
          padding: EdgeInsets.zero,
          constraints: const BoxConstraints(),
          tooltip: "Add Service",
        ),
      ],
    );
  }

  // Placeholder for empty state
  Widget _buildEmptyState() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(vertical: 40),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.post_add_rounded, size: 48, color: Colors.grey.shade300),
          const SizedBox(height: 12),
          Text(
            'No services added yet',
            style: TextStyle(
              color: Colors.grey.shade500,
              fontSize: 14,
              fontWeight: FontWeight.w500,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            'Tap + to add a new service',
            style: TextStyle(color: Colors.grey.shade400, fontSize: 12),
          ),
        ],
      ),
    );
  }

  // Dynamic Service Card
  Widget _buildServiceCard(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    final docId = doc.id;
    final title = data['title'] ?? 'Service';
    final category = data['category'] ?? 'Other';
    final steps = data['steps'] ?? '';
    final config =
        categoryConfig[category] ??
        {'color': const Color(0xFF9E9E9E), 'icon': Icons.info};

    final isExpanded = _expandedStates[docId] ?? false;

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        children: [
          // Service Header (Tile)
          ListTile(
            leading: Container(
              height: 40,
              width: 40,
              decoration: BoxDecoration(
                // NOTE: Uses a Color property, which is safe.
                color: (config['color'] as Color).withOpacity(0.1),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Icon(
                config['icon'] as IconData,
                color: config['color'] as Color,
                size: 20,
              ),
            ),
            title: Text(
              title,
              style: const TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w600,
                color: Colors.black87,
              ),
            ),
            subtitle: Text(
              category,
              style: TextStyle(fontSize: 12, color: Colors.grey.shade500),
            ),
            trailing: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                IconButton(
                  onPressed: () => _showEditServiceDialog(doc),
                  icon: const Icon(
                    Icons.edit_outlined,
                    color: Colors.grey,
                    size: 20,
                  ),
                  tooltip: "Edit",
                  padding: EdgeInsets.zero,
                  constraints: const BoxConstraints(),
                ),
                const SizedBox(width: 12),
                IconButton(
                  onPressed: () => _showDeleteConfirmDialog(docId),
                  icon: const Icon(
                    Icons.delete_outline,
                    color: Colors.redAccent,
                    size: 20,
                  ),
                  tooltip: "Delete",
                  padding: EdgeInsets.zero,
                  constraints: const BoxConstraints(),
                ),
                const SizedBox(width: 12),
                InkWell(
                  onTap: () {
                    setState(() {
                      _expandedStates[docId] = !isExpanded;
                    });
                  },
                  child: Icon(
                    isExpanded ? Icons.expand_less : Icons.expand_more,
                    color: Colors.grey.shade600,
                  ),
                ),
              ],
            ),
            onTap: () {
              setState(() {
                _expandedStates[docId] = !isExpanded;
              });
            },
          ),

          if (isExpanded)
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Colors.grey.shade50,
                borderRadius: const BorderRadius.only(
                  bottomLeft: Radius.circular(12),
                  bottomRight: Radius.circular(12),
                ),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'Steps / Requirements:',
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 14,
                      color: Colors.black87,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    steps,
                    style: TextStyle(
                      fontSize: 14,
                      color: Colors.grey.shade700,
                      height: 1.5,
                    ),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildBottomNavBar() {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 10,
            offset: const Offset(0, -5),
          ),
        ],
      ),
      child: BottomNavigationBar(
        currentIndex: _selectedIndex,
        type: BottomNavigationBarType.fixed,
        selectedItemColor: Colors.blue,
        unselectedItemColor: Colors.grey.shade400,
        backgroundColor: Colors.white,
        showSelectedLabels: true,
        showUnselectedLabels: true,
        selectedLabelStyle: const TextStyle(
          fontWeight: FontWeight.w600,
          fontSize: 12,
        ),
        unselectedLabelStyle: const TextStyle(
          fontWeight: FontWeight.w500,
          fontSize: 12,
        ),
        elevation: 0,
        onTap: _onItemTapped,
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.home_rounded),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.phone_rounded),
            label: 'Emergency',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.campaign_rounded),
            label: 'Updates',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.people_alt_rounded),
            label: 'People',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person_rounded),
            label: 'Profile',
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    Widget mobileContent = Scaffold(
      // Attach the key to the ScaffoldMessenger
      body: ScaffoldMessenger(
        key: _scaffoldMessengerKey,
        child: Scaffold(
          backgroundColor: const Color(0xFFF8F9FA),
          body: SafeArea(
            child: Column(
              children: [
                _buildHeader(),
                Expanded(
                  child: SingleChildScrollView(
                    padding: const EdgeInsets.all(20),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        _buildSearchBar(),
                        const SizedBox(height: 24),
                        _buildSectionTitle(
                          "Barangay Services",
                          _showAddServiceDialog,
                        ),
                        const SizedBox(height: 16),
                        StreamBuilder<QuerySnapshot>(
                          stream: _servicesStream,
                          builder: (context, snapshot) {
                            if (snapshot.connectionState ==
                                ConnectionState.waiting) {
                              return const Center(
                                child: Padding(
                                  padding: EdgeInsets.all(20),
                                  child: CircularProgressIndicator(),
                                ),
                              );
                            }
                            if (snapshot.hasError) {
                              return const Text("Error loading services");
                            }

                            final docs = snapshot.data?.docs ?? [];

                            // Fix: Functional Search Filter
                            final filteredDocs = _searchQuery.isEmpty
                                ? docs
                                : docs.where((doc) {
                                    final data =
                                        doc.data() as Map<String, dynamic>;
                                    final title = (data['title'] ?? '')
                                        .toString()
                                        .toLowerCase();
                                    final category = (data['category'] ?? '')
                                        .toString()
                                        .toLowerCase();
                                    return title.contains(_searchQuery) ||
                                        category.contains(_searchQuery);
                                  }).toList();

                            if (filteredDocs.isEmpty) {
                              if (_searchQuery.isNotEmpty) {
                                return Center(
                                  child: Padding(
                                    padding: const EdgeInsets.only(top: 40),
                                    child: Text(
                                      "No matching services found",
                                      style: TextStyle(
                                        color: Colors.grey.shade500,
                                      ),
                                    ),
                                  ),
                                );
                              }
                              return _buildEmptyState();
                            }

                            return Column(
                              children: filteredDocs
                                  .map((doc) => _buildServiceCard(doc))
                                  .toList(),
                            );
                          },
                        ),
                        const SizedBox(height: 40),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
          bottomNavigationBar: _buildBottomNavBar(),
        ),
      ),
    );

    if (kIsWeb) {
      return PhoneFrame(child: mobileContent);
    }
    return mobileContent;
  }
}

// --- PHONE FRAME ---
class PhoneFrame extends StatelessWidget {
  final Widget child;
  const PhoneFrame({super.key, required this.child});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF2F2F7),
      body: Center(
        child: Container(
          width: 375,
          height: 812,
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(40),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.1),
                blurRadius: 30,
                spreadRadius: 5,
                offset: const Offset(0, 10),
              ),
            ],
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(40),
            child: child,
          ),
        ),
      ),
    );
  }
}
